/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//KEY RING

COPY ~%MOD_FOLDER%/items/containers~ ~override~

COPY_EXISTING ~c0keyr.itm~ ~override~
SAY NAME1 ~Key Ring~
SAY NAME2 ~Key Ring~
SAY UNIDENTIFIED_DESC ~A latch on this heavy steel ring allows it to open on a hinge. Dozens of keys may be threaded on the ring to keep them organized.

STATISTICS:

Weight: 0~
SAY DESC ~A latch on this heavy steel ring allows it to open on a hinge. Dozens of keys may be threaded on the ring to keep them organized.

STATISTICS:

Weight: 0~

COPY_EXISTING ~c0keyr.sto~ ~override~
SAY 0xc ~Key Ring~

COPY_EXISTING ~ARLED.sto~ ~override~
ADD_STORE_ITEM ~bdkeyr~ #0 #0 #0 ~IDENTIFIED~ #1

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//MONK

COPY ~%MOD_FOLDER%/monk/items~ ~OVERRIDE~

COPY_EXISTING ~C0MNRO01.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +1~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 6

Weight: 4~

COPY_EXISTING ~C0MNRO01.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +1~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 6

Weight: 4~

COPY_EXISTING ~C0MNRO02.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +2~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 5

Weight: 4~

COPY_EXISTING ~C0MNRO03.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +3~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 4

Weight: 4~

COPY_EXISTING ~C0MNRO04.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +4~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 3

Weight: 4~

COPY_EXISTING ~C0MNRO05.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Shining Hand +5~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~The Shining Hand Monastery in Vaasa has made an impressive reputation, and a small fortune, designing these robes. Demand has spread across many nations, such that different variations on the similar robes keep the monks hard at work. The robes increase a monk's senses to such a degree that she can focus on her opponent and move her body to absorb blows.

Equipped abilities:
– Armor Class: 2

Weight: 4~

COPY_EXISTING ~C0MNRO06.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Old Order~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~Whatever the motives of the Monks of the Old Order might be, no one doubts that they are keenly, defensively minded. Rumor has it that the masters of the order attain ranks by being able to survive a beating by an Ogre, without ever raising a hand in defense. True or not, these robes, produced by the order to fund monasteries, are the trade mark of any monk who would survive in the frontlines of combat, against an enemy clad in armor.

Equipped abilities:
– Armor Class: +2
– Physical Resistance: +10%

Weight: 4~

COPY_EXISTING ~C0MNRO07.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Dark Moon~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~When she was a young student in the monastery of the Dark Moon monks, Beyl Van Yoren's teachers would constantly urge her to move faster and faster. They were finally appeased, when she suddenly began to be able to hit them four shots for every one of theirs. Despite her speed, Beyl found she had trouble concentrating on lessons, usually because she was moving so much faster than everyone else, that she would often grow bored and restless. Eventually she gave up the robes and the monastery to go and live with the wizard, whom she had traded 'personal favors' with for months, to earn the robes.

Equipped abilities:
– Haste
– Saving Throws: -1

Weight: 4~

COPY_EXISTING ~C0MNRO08.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Broken Ones~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~These bulky robes are worn by followers of Ilmater, god of endurance and martyrdom. Monks of the Order of the Broken Ones follow a code of selflessness, raising their fists to defend the innocents rather than deal harm to others. These robes are reflective of their pacifistic ideology, designed to protect its wearer from danger.

Equipped abilities:
– Armor Class: +2
– Maximum Hit Points: +15
– Damage: -1
– Immunity to Poison

Weight: 4~

COPY_EXISTING ~C0MNRO09.ITM~ OVERRIDE
SAY NAME1 ~Monk Robes~
SAY NAME2 ~Robes of the Inner Eye~
SAY UNIDENTIFIED_DESC ~Robes worn by monks of various monastic orders.

STATISTICS:

Weight: 4~
SAY DESC ~Yang Xun, a Shou martial artist, was a gifted student of the Heavenly Dragon school whose talent led him to be scouted for a respected position in the Emperor's personal guard. Unfortunately, his sibling students, envious of his potential, conspired to cut his future short by poisoning his wine with a toxin that rendered him nearly blind and unable to continue his training. His master, unwilling to see his talented pupil's life wasted, brought him to a monastery to be cared for by the esteemed abbot, his closest friend. Five years later, Yang made the journey back to his school to visit his former master where his rivals, fearful of retribution, attempted to ambush him en route under the cover of darkness, only for a blindfolded Yang to effortlessly dodge their blades, spears and knives as though possessing a sixth sense, until all his opponents lay broken and defeated, without a single stain or tear on Yang's initiate robes.

Equipped abilities:
– Armor Class: +2 vs. slashing and piercing attacks
– Protects against critical hits

Weight: 4~

COPY_EXISTING ~C0MNBR01.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Yellow Rose +1~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Also referred to as the Disciples of the Saint Sollars, the Monastic Order of the Yellow Rose is known equally for its acts of great loyalty to its allies and those of great destruction to its enemies. Monks of this Order frequently travel alongside paladins of Ilmater, serving as trusted guides and companions to these knights of the suffering lord.

Equipped abilities:
– Fist THAC0: +1
– Unarmed attacks strike as +1 weapons and deal 1 additional electrical damage

Weight: 2~

COPY_EXISTING ~C0MNBR02.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Yellow Rose +2~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Also referred to as the Disciples of the Saint Sollars, the Monastic Order of the Yellow Rose is known equally for its acts of great loyalty to its allies and those of great destruction to its enemies. Monks of this Order frequently travel alongside paladins of Ilmater, serving as trusted guides and companions to these knights of the suffering lord.

Equipped abilities:
– Fist THAC0: +2
– Unarmed attacks strike as +2 weapons and deal 2 additional electrical damage

Weight: 2~

COPY_EXISTING ~C0MNBR03.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Yellow Rose +3~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Also referred to as the Disciples of the Saint Sollars, the Monastic Order of the Yellow Rose is known equally for its acts of great loyalty to its allies and those of great destruction to its enemies. Monks of this Order frequently travel alongside paladins of Ilmater, serving as trusted guides and companions to these knights of the suffering lord.

Equipped abilities:
– Fist THAC0: +3
– Unarmed attacks strike as +3 weapons and deal 3 additional electrical damage

Weight: 2~

COPY_EXISTING ~C0MNBR04.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Long Death +1~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Founded in distant Thay, the Monastic Order of the Long Death celebrates the passage from life to lifelessness in all of its forms. It is said by those who have survived encounters with the Order that the grip of its adherents is like the icy touch of death itself, not soon to be forgotten.

Equipped abilities:
– Fist THAC0: +1
– Unarmed attacks strike as +1 weapons and deal 1 additional cold damage

Weight: 2~

COPY_EXISTING ~C0MNBR05.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Long Death +2~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Founded in distant Thay, the Monastic Order of the Long Death celebrates the passage from life to lifelessness in all of its forms. It is said by those who have survived encounters with the Order that the grip of its adherents is like the icy touch of death itself, not soon to be forgotten.

Equipped abilities:
– Fist THAC0: +2
– Unarmed attacks strike as +2 weapons and deal 2 additional cold damage

Weight: 2~

COPY_EXISTING ~C0MNBR06.ITM~ OVERRIDE
SAY NAME1 ~Gauntlets~
SAY NAME2 ~Gloves of the Long Death +3~
SAY UNIDENTIFIED_DESC ~Gauntlets are armored gloves. They can be made of leather, metal plates, or chain mail. Every suit of armor is assumed to include gauntlets of an appropriate type. Magical gauntlets tend to be finer, lighter, and more easily worn than normal varieties.

STATISTICS:

Weight: 2~
SAY DESC ~Founded in distant Thay, the Monastic Order of the Long Death celebrates the passage from life to lifelessness in all of its forms. It is said by those who have survived encounters with the Order that the grip of its adherents is like the icy touch of death itself, not soon to be forgotten.

Equipped abilities:
– Fist THAC0: +3
– Unarmed attacks strike as +3 weapons and deal 3 additional cold damage

Weight: 2~

ACTION_IF FILE_EXISTS_IN_GAME ~tem3402.sto~ THEN BEGIN
COPY_EXISTING ~tem3402.sto~ ~override~
ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~stoblack.sto~ THEN BEGIN
COPY_EXISTING ~stoblack.sto~ ~override~
ADD_STORE_ITEM ~c0mnbr05~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~AR5001.ARE~ BEGIN
    COPY_EXISTING ~AR5001.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 1
      STR_VAR
        item_to_add = ~c0mnbr04~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~AR2615.ARE~ BEGIN
    COPY_EXISTING ~AR2615.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 2
      STR_VAR
        item_to_add = ~c0mnbr02~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~tem4802.sto~ THEN BEGIN
COPY_EXISTING ~tem4802.sto~ ~override~
ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro03~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~taerum.sto~ THEN BEGIN
COPY_EXISTING ~taerum.sto~ ~override~
ADD_STORE_ITEM ~c0mnro09~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdkazzre.sto~ THEN BEGIN
COPY_EXISTING ~bdkazzre.sto~ ~override~
ADD_STORE_ITEM ~c0mnro05~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bddosia.sto~ THEN BEGIN
COPY_EXISTING ~bddosia.sto~ ~override~
ADD_STORE_ITEM ~c0mnro08~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbeleg4.sto~ THEN BEGIN
COPY_EXISTING ~bdbeleg4.sto~ ~override~
ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro03~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr02~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr04~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnbr05~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdinsa06.cre~ THEN BEGIN
COPY_EXISTING ~bdinsa06.cre~ ~override~
ADD_CRE_ITEM ~c0mnbr03~ #0 #0 #0 ~NONE~ ~GLOVES~
END

ACTION_IF GAME_INCLUDES ~SOD~ THEN BEGIN
COPY ~%MOD_FOLDER%/MonkRevision/creatures/C0MNEV01.cre~ ~override~
SAY NAME1 ~Black Hand~
SAY NAME2 ~Black Hand~
COPY_EXISTING BD5300.are override
  LPF fj_are_structure
    INT_VAR
    fj_loc_x          = 1417
    fj_loc_y          = 1131
    fj_dest_x         = 1417
    fj_dest_y         = 1131
    fj_animation      = 0x6500 
    fj_orientation    = 0     
    STR_VAR
    fj_structure_type = actor
    fj_name           = Black Hand
    fj_cre_resref     = c0mnev01
  END
END

// BG2

ACTION_FOR_EACH temple_stores IN BHELM DAWNMAS HELMPR SLILMAT WILMAT TEMHELM TEMLATH BEGIN
ACTION_IF FILE_EXISTS_IN_GAME ~%temple_stores%.sto~ THEN BEGIN
  COPY_EXISTING ~%temple_stores%.sto~ ~override~
    ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnro03~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnbr01~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnbr02~ #0 #0 #0 ~IDENTIFIED~ #1

  END
  END

ACTION_FOR_EACH temple_stores_evil IN TEMTALOS PPUMB01 BEGIN
ACTION_IF FILE_EXISTS_IN_GAME ~%temple_stores_evil%.sto~ THEN BEGIN
  COPY_EXISTING ~%temple_stores_evil%.sto~ ~override~
    ADD_STORE_ITEM ~c0mnro01~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnro02~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnro03~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnbr04~ #0 #0 #0 ~IDENTIFIED~ #1
    ADD_STORE_ITEM ~c0mnbr05~ #0 #0 #0 ~IDENTIFIED~ #1

  END
  END

ACTION_IF FILE_EXISTS_IN_GAME ~AR0203.are~ THEN BEGIN
COPY_EXISTING ~AR0203.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 1
      STR_VAR
        item_to_add = ~C0MNBR03~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~AR1202.are~ THEN BEGIN
COPY_EXISTING ~AR1202.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 7
      STR_VAR
        item_to_add = ~C0MNBR06~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~OH4101.are~ THEN BEGIN
COPY_EXISTING ~OH4101.are~ ~override~
      LPF ADD_AREA_ITEM
      INT_VAR
        container_to_add_to = 1
      STR_VAR
        item_to_add = ~C0MNRO04~
      END
END

ACTION_IF FILE_EXISTS_IN_GAME ~SLILMAT.sto~ THEN BEGIN
COPY_EXISTING ~SLILMAT.sto~ ~override~
ADD_STORE_ITEM ~c0mnro08~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~ribald3.sto~ THEN BEGIN
COPY_EXISTING ~ribald3.sto~ ~override~
ADD_STORE_ITEM ~c0mnro05~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro06~ #0 #0 #0 ~IDENTIFIED~ #1
ADD_STORE_ITEM ~c0mnro09~ #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~OHRBRAIT.cre~ THEN BEGIN
COPY_EXISTING ~OHRBRAIT.cre~ ~override~
ADD_CRE_ITEM ~c0mnro08~ #0 #0 #0 ~NONE~ ~ARMOR~
END